"""
Test the loading time for 2 forms of storage:
    1. gexf file.
    2. h5 and csv file generated by graph_preprocess.py
"""
import argparse
from hic_graph import HicGraph

def get_args():
    parser = argparse.ArgumentParser('python')

    parser.add_argument('-edge_dir',
                        default='../../preprocess-output/final_edge.h5',
                        required=False,
                        help='directory of output edge file.')  

    parser.add_argument('-node_dir',
                        default='../../preprocess-output/final_node.csv',
                        required=False,
                        help='directory of output edge file.')  
                 
    return parser.parse_args()


if __name__ == "__main__":
    args = get_args()
    edge_dir = args.edge_dir
    node_dir = args.node_dir
    hic_graph = HicGraph(edge_dir, node_dir, None)
    hic_graph.load_graph()
